/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ErpWcSideDrawer {
        "open": boolean;
        "openSide": () => Promise<void>;
        "sideTitle": string;
    }
}
declare global {
    interface HTMLErpWcSideDrawerElement extends Components.ErpWcSideDrawer, HTMLStencilElement {
    }
    var HTMLErpWcSideDrawerElement: {
        prototype: HTMLErpWcSideDrawerElement;
        new (): HTMLErpWcSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "erp-wc-side-drawer": HTMLErpWcSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface ErpWcSideDrawer {
        "open"?: boolean;
        "sideTitle"?: string;
    }
    interface IntrinsicElements {
        "erp-wc-side-drawer": ErpWcSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "erp-wc-side-drawer": LocalJSX.ErpWcSideDrawer & JSXBase.HTMLAttributes<HTMLErpWcSideDrawerElement>;
        }
    }
}
